spring:
 datasource:
  url : jdbc:h2://localhost/trgdb
  #  driver-class-name : com.mysql.jdbc.Driver
   # url: jdbc:mysql://localhost/trgdb      
    #username : root
    #password : root123
  #jpa:
   # hibernate:
    #  ddl-auto: update
      
      
 
